[".oh-my-zsh-custom/completions/_eza"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" "completions-*.tar.gz" | quote }}
refreshPeriod = "168h"
stripComponents = 3
path = "_eza"
