[".local/bin/youtube-dl"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "yt-dlp/yt-dlp" "yt-dlp_linux"  | quote }}
refreshPeriod = "168h"
executable = true

[".local/bin/bookmarks"]
type = "file"
url = "https://raw.githubusercontent.com/stoeps13/bookmarks.txt/refs/heads/main/bin/bookmarks"
executable = true
refreshPeriod = "168h"

[".local/bin/saul"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "DeprecatedLuar/better-curl-saul" "saul-linux-amd64"  | quote }}
refreshPeriod = "168h"
executable = true

["data/sectools/linpeas_linux_amd64"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "peass-ng/PEASS-ng" "linpeas_linux_amd64"  | quote }}
refreshPeriod = "168h"
executable = true

["data/sectools/winPEASx64.exe"]
type = "file"
url = {{ gitHubLatestReleaseAssetURL "peass-ng/PEASS-ng" "winPEASx64.exe"  | quote }}
refreshPeriod = "168h"
executable = true

[".local/bin/git-secrets"]
type = "file"
url = "https://raw.githubusercontent.com/awslabs/git-secrets/refs/heads/master/git-secrets"
executable = true
refreshPeriod = "168h"

[".local/share/task/hooks/on-add-pirate"]
type = "file"
url = "https://raw.githubusercontent.com/tbabej/taskpirate/refs/heads/master/on-add-pirate"
executable = true
refreshPeriod = "168h"

[".local/share/task/hooks/on-modify-pirate"]
type = "file"
url = "https://raw.githubusercontent.com/tbabej/taskpirate/refs/heads/master/on-modify-pirate"
executable = true
refreshPeriod = "168h"
