# [".config/nvim"]
# type = "git-repo"
# #url = "git@github.com:stoeps13/kickstart.nvim.git"
# url = "https://github.com/stoeps13/kickstart.nvim.git"
# refreshPeriod = "168h"

["data/SecLists"]
type = "git-repo"
url = "https://github.com/danielmiessler/SecLists.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".local/share/task/hooks/default-time"]
type = "git-repo"
url = "https://github.com/tbabej/taskwarrior-default-date-time-hook.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]
