[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "168h"

[".oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"

[".oh-my-zsh-custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.git"
refreshPeriod = "168h"

# [".config/nvim"]
# type = "git-repo"
# #url = "git@github.com:stoeps13/kickstart.nvim.git"
# url = "https://github.com/stoeps13/kickstart.nvim.git"
# refreshPeriod = "168h"

["data/SecLists"]
type = "git-repo"
url = "https://github.com/danielmiessler/SecLists.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".local/share/task/hooks/default-time"]
type = "git-repo"
url = "https://github.com/tbabej/taskwarrior-default-date-time-hook.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]

[".liquidprompt"]
type = "git-repo"
url = "https://github.com/liquidprompt/liquidprompt.git"
refreshPeriod = "168h"
clone.args = ["--branch", "stable"]

