[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod = "168h"

[".oh-my-zsh-custom/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod = "168h"

[".oh-my-zsh-custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod = "168h"

[".fzf"]
  type = "git-repo"
  url = "https://github.com/junegunn/fzf.git"
  refreshPeriod = "168h"

[".local/share"]
  type = "archive"
  url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
  refreshPeriod = "168h"

{{ $hugo_version := "v0.145.2" -}}
[".local/bin/hugo"]
    type = "file"
    url = "https://github.com/gohugoio/hugo/releases/download/{{ $hugo_version }}/hugo_{{ $hugo_version }}_{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/hugo".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "hugo"]
