davmail.ssl.keystoreType=
davmail.ssl.keystorePass=
davmail.proxyPassword=
davmail.smtpPort=1025
davmail.enableKerberos=false
davmail.folderSizeLimit=
davmail.forceActiveSyncUpdate=false
davmail.imapAutoExpunge=true
davmail.useSystemProxies=false
davmail.proxyUser=
davmail.ssl.nosecuresmtp=false
davmail.caldavPastDelay=0
davmail.ssl.keyPass=
log4j.logger.httpclient.wire=WARN
davmail.noProxyFor=
davmail.server=false
davmail.popMarkReadOnRetr=false
davmail.ssl.nosecureimap=false
davmail.disableTrayActivitySwitch=false
davmail.caldavAutoSchedule=true
davmail.enableProxy=false
davmail.proxyPort=
davmail.mode=O365Manual
davmail.smtpSaveInSent=true
davmail.bindAddress=
davmail.ssl.nosecurepop=false
davmail.ssl.pkcs11Library=
log4j.rootLogger=WARN
davmail.ssl.keystoreFile=
log4j.logger.davmail=DEBUG
davmail.ssl.clientKeystoreType=
davmail.clientSoTimeout=
davmail.ssl.pkcs11Config=
davmail.imapPort=1143
davmail.ssl.clientKeystorePass=
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
davmail.sentKeepDelay=0
davmail.ssl.nosecureldap=false
davmail.imapAlwaysApproxMsgSize=false
davmail.ssl.nosecurecaldav=false
davmail.popPort=
davmail.showStartupBanner=true
log4j.logger.httpclient=WARN
davmail.proxyHost=
davmail.ldapPort=1389
davmail.server.certificate.hash=
davmail.disableGuiNotifications=false
davmail.imapIdleDelay=30
davmail.allowRemote=false
davmail.disableUpdateCheck=false
davmail.caldavPort=1080
davmail.enableKeepAlive=true
davmail.ssl.clientKeystoreFile=
davmail.logFilePath=/home/stoeps/.davmail
davmail.carddavReadPhoto=true
davmail.keepDelay=30
davmail.caldavAlarmSound=
davmail.oauth.tenantId=
davmail.logFileSize=
log4j.logger.org.apache.http.conn.ssl=WARN
log4j.logger.org.apache.http=WARN
davmail.defaultDomain=
davmail.caldavEditNotifications=false
davmail.oauth.redirectUri=
log4j.logger.org.apache.http.wire=WARN
davmail.oauth.clientId=
davmail.oauth.stoeps@vegardit.com={AES}FIlH/4psBxz92surMB0YAhCmKKTmJ6VLgfIrpXjSym9jNo+F6O2BtRNEAm5aHV9fnR6xN+HUMwqNDFj+472OEVvG4jucf3TeuZzszsi2USNN+LKVpbcNtFIzG0SP/dJVK6ziZ1UW5BJYMEYoZABIh2sjs2SqrhuQtkhoZkaw5hui1obAX+OV8V16HpRO9l+Uz1kcwFdnXOGH7YgDLE6huvaXPhfDrveCWMBcWxBbtlqZF1tPqhwcFNdowTThuUsEnec6/MuHcGS1icPkaUnV9MZkmA3UovvjLg4fds1MguOlROOiUPJsfkcre7zRJvpAQUCXc1tKDLGhz50/GQSZwA2o6C2KaogYgqhIi20gXoeEP/WGxQZStEZwpiNEyHLl/XMCTxMuRMhlBsDun0uTVzeZen/Cx9hx6lBwGCOV4HGCB4/L8mTM9nOrBCzDJAfwwFpiWjlVg9816aOeYF0cfYSoDyLTp9tNwZASZ0abynUrxQyEbZVMi8JYoIQXn/Z1N7f0+MQiAYMETvbEdsex9U+QD8Kradz2SS2P7wy3GQd1Oh+y24uXg3LGReODY8cGTog9J4+Y36dkk0OtTCweh+bF001oapXe/OOKCjmQbNxORYKdi785i5Amf65A481dQlPzWbBMz8rl6d1HhVbbn7ma5qrnSyFuSst29gK8IxA3qJLBobTnaUAusEd3kilZFQn/bC3Z0zEbuKduKkDWb3OeOUskGphUUgOr6OU2iUE7vdn7LaHEiLo7fZoKVE7PMRYTzfo+XLXtlE4DNwQl+tWpywcXaJU1hjkHweck6IOaHupWWiAL/w1GMZ1IVChhrv4CQaylB79ZiCVko572fKmuQaRlA7GhdXmnUfv/Yh62tZIN06UbuAYKMTWclqCrqOY+jWkQHTOjuOgnMRN7hSNuq7s5DO4eLcpeAaQwkN8nJpxHMzXjcEbT9IwbqQDaCJ3VjNs3fK8E/wyq8Ibm8mFIR1ojGQofgDm/kz0h0AplRALSQoYWVJrHh0QPkcaJ2+Evq5a9ml9IvmS9g7DaHj6dQNUPBGBp5ogXc2dMYNZNju9DoNS5f5SdYWgxNbBeDbOa54DUDJNxNf6Ox/fx1wwKECY+6CPoJj2xXxbv8ng4OsjFyyElra+ECC+TS9xbCKTlkZgosiMT00V+GmUFYU7l5+o6NBfHvjX3frHc558=
>>>>>>>=b5bc9d2ebb50a7592896cad1eae2e689a0229a49
davmail.oauth.stoeps@vegardit.com.refreshToken={AES}FIlH/4psBxz92surMB0YAhCmKKTmJ6VLgfIrpXjSym9jNo+F6O2BtRNEAm5aHV9fnR6xN+HUMwqNDFj+472OEVvG4jucf3TeuZzszsi2USNN+LKVpbcNtFIzG0SP/dJV1WKgDkZvyRjzOcqZY4Y4zoPr56PVq0eT23gkHql2nMIWOfUAPgj4mRMz0riwBkM1f0rudDQPuUYdqhdU0D9b31s/0GuY0nPuNnhFRC9Mv1L8GslxjzdUZ7gvGV+M6HgGjFLUwdImeOB4cVwPIhBCWj5Cc15K19L1k9Cll8o/4ukEn5SpUIO+mFOwQGswlLRImcuNA4HYYDwptbvDIFrEOQCBDg7+foF87wDVInekP1KKmNkks7cHyxn3QNPiidL7fQSxZ3D5NhKJnKjXgOWr0wFRF7C0EnSUHL50vpjfaN9OftjLjoxUNEyeMIinqKhyxFOep38KJ0DTE6TfzuCpi+4PddmFTm5ViKK8YY6DeqJsTJFItTb3qW6Mdhcu/TuMgsK/40Ux98ibviST6k/Kf/W7Dqodhiwq5wj625ukphVs9KPRFQb0jMyIsFVW3BF/CPXGvff1dQajUk69ufPQXQZGK4THQ71bCwKeh4HoJHH3rXZ9wS7mxzjt5xpSo1V4vwYItubF/cNBo7BYIqmsh0YZsAIxl87p0BKDPi2Ib8dym720Vsev7GsW7/YEmHqGjIvDMVkh5QXSM5BqTWW9/AkFqCM7xADUxRvXXwpelUghQbbjWqh60IWRdr6bmnwpTccmiX0r+LA8Keyyb4DmM8JNFjjyeHghJ7DAJMCK66uB8T89Ik6K4a5k9T7B4MiDGLvL1EXLdnZlaPBoZSf0tQBh5Nvb+AnZ9/7301gbHM5h4jnnfO3utmAoDgJQ2VHW2MbqFpo++rY7oPMfj5M+DBr8jBHOi0rGFgZXD/x4IkWrYamvDnUBq1/4Pza+Cwoq07bgCgIgALKtUs3B3gqGugdNeaFoX7W40v8OBt25nlAO43A/aBO6JTQaa1AxAazrmA+2u8+bBfT0PQVHwFE9XwSZ02PyxmvXi0gpM3Mbx0O3Dku4nxWOSS9Fm0Rylmy7S94yYNZFdqcDHYWdwVdi0DTlTeGxQlfppL6vtGWnU20DbA6bicmcCwDE4jBH870AhKBJtl4+rGzbizEbDfcUUxWk1VptuXe5CsumZMgZFGs=
<<<<<<<=HEAD
=======
