[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[window]
opacity = 0.8
blur = true

[font]
normal = {family = "JetBrains Mono", style = "Regular"}
offset = {y = -1}

[mouse]
bindings = [
  { mouse = "Right", action = "Copy" },
]

[selection]
save_to_clipboard = true
