cursor #e1e2e8
cursor_text_color #c3c7cf

foreground            #e1e2e8
background            #101418
selection_foreground  #253140
selection_background  #bac8db
url_color             #a0cafd

color0   #101418
color1   #ff729c
color2   #7efd8f
color3   #fff772
color4   #86b6f0
color5   #184975
color6   #a0cafd
color7   #eff7ff
color8   #3e4347
color9   #ff9fbb
color10  #a5ffb1
color11  #fffaa5
color12  #afd3ff
color13  #bddbff
color14  #d4e7ff
color15  #f8fbff
